version: '2'

services:
  nodemain:
    build: .
    entrypoint: 
    command: "/smudge -ip 10.5.0.2 -port 9999"
    ports:
      - 9990:9999
    networks:
      smudgeNetwork:
        ipv4_address: 10.5.0.2

  node001:
    build: .
    command: "/smudge -node 10.5.0.2 -port 9999 -ip 10.5.0.3"
    ports:
      - 9991:9999
    networks:
      smudgeNetwork:
        ipv4_address: 10.5.0.3

  node002:
    build: .
    command: "/smudge -node 10.5.0.2 -port 9999 -ip 10.5.0.4"
    ports:
      - 9992:9999
    networks:
      smudgeNetwork:
        ipv4_address: 10.5.0.4
networks:
  smudgeNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1